version: '3'

services:  
  nicosia_roads:
    build: "."
    command: python -u main.py               
    external_links:
      - postgres
    networks:
      - mynet

networks:
  mynet:
    external:
      name: mynet          